/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;


import java.awt.Color;

/**
 *
 * @author Totto
 */
public class JF_Calendario extends javax.swing.JFrame {

    /**
     * Creates new form Calendario
     */
    public JF_Calendario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtn_lunes8_10 = new javax.swing.JToggleButton();
        jlbl_lunes8_10 = new javax.swing.JLabel();
        jbtn_martes8_10 = new javax.swing.JToggleButton();
        jlbl_martes8_10 = new javax.swing.JLabel();
        jbtn_miercoles8_10 = new javax.swing.JToggleButton();
        jlbl_miercoles8_10 = new javax.swing.JLabel();
        jlbl_jueves8_10 = new javax.swing.JLabel();
        jbtn_jueves8_10 = new javax.swing.JToggleButton();
        jbtn_viernes8_10 = new javax.swing.JToggleButton();
        jlbl_viernes8_10 = new javax.swing.JLabel();
        jbtn_lunes10_12 = new javax.swing.JToggleButton();
        jlbl_lunes10_12 = new javax.swing.JLabel();
        jbtn_lunes12_14 = new javax.swing.JToggleButton();
        jlbl_lunes12_14 = new javax.swing.JLabel();
        jbtn_lunes14_16 = new javax.swing.JToggleButton();
        jlbl_lunes14_16 = new javax.swing.JLabel();
        jbtn_lunes16_18 = new javax.swing.JToggleButton();
        jlbl_lunes16_18 = new javax.swing.JLabel();
        jlbl_martes16_18 = new javax.swing.JLabel();
        jbtn_martes16_18 = new javax.swing.JToggleButton();
        jlbl_martes14_16 = new javax.swing.JLabel();
        jbtn_martes14_16 = new javax.swing.JToggleButton();
        jlbl_martes12_14 = new javax.swing.JLabel();
        jbtn_martes12_14 = new javax.swing.JToggleButton();
        jlbl_martes10_12 = new javax.swing.JLabel();
        jbtn_martes10_12 = new javax.swing.JToggleButton();
        jlbl_lunes8_24 = new javax.swing.JLabel();
        jbtn_miercoles16_18 = new javax.swing.JToggleButton();
        jlbl_miercoles14_16 = new javax.swing.JLabel();
        jbtn_miercoles14_16 = new javax.swing.JToggleButton();
        jlbl_miercoles12_14 = new javax.swing.JLabel();
        jbtn_miercoles12_14 = new javax.swing.JToggleButton();
        jlbl_miercoles10_12 = new javax.swing.JLabel();
        jbtn_miercoles10_12 = new javax.swing.JToggleButton();
        jlbl_jueves16_18 = new javax.swing.JLabel();
        jbtn_jueves16_18 = new javax.swing.JToggleButton();
        jlbl_jueves14_16 = new javax.swing.JLabel();
        jbtn_jueves14_16 = new javax.swing.JToggleButton();
        jlbl_jueves12_14 = new javax.swing.JLabel();
        jbtn_jueves12_14 = new javax.swing.JToggleButton();
        jlbl_jueves10_12 = new javax.swing.JLabel();
        jbtn_jueves10_12 = new javax.swing.JToggleButton();
        jlbl_viernes16_18 = new javax.swing.JLabel();
        jbtn_viernes16_18 = new javax.swing.JToggleButton();
        jlbl_viernes14_16 = new javax.swing.JLabel();
        jbtn_viernes14_16 = new javax.swing.JToggleButton();
        jlbl_viernes12_14 = new javax.swing.JLabel();
        jbtn_viernes12_14 = new javax.swing.JToggleButton();
        jlbl_viernes10_12 = new javax.swing.JLabel();
        jbtn_viernes10_12 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_lunes8_14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jbtn_Limpiar = new javax.swing.JButton();
        jbtn_cerrarSesion = new javax.swing.JButton();
        jbtn_cerrar_Sesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setText("Lista de Reservas de Salas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Martes");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Miercoles");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Lunes");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Jueves");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Viernes");

        jbtn_lunes8_10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_lunes8_10.setText("Reservar");
        jbtn_lunes8_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_lunes8_10ActionPerformed(evt);
            }
        });

        jlbl_lunes8_10.setText("Ewans Ewoldt");

        jbtn_martes8_10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_martes8_10.setText("Reservar");
        jbtn_martes8_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_martes8_10ActionPerformed(evt);
            }
        });

        jlbl_martes8_10.setText(" ");

        jbtn_miercoles8_10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_miercoles8_10.setText("Reservar");
        jbtn_miercoles8_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_miercoles8_10ActionPerformed(evt);
            }
        });

        jlbl_miercoles8_10.setText(" ");

        jlbl_jueves8_10.setText(" ");

        jbtn_jueves8_10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_jueves8_10.setText("Reservar");
        jbtn_jueves8_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_jueves8_10ActionPerformed(evt);
            }
        });

        jbtn_viernes8_10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_viernes8_10.setText("Reservar");
        jbtn_viernes8_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viernes8_10ActionPerformed(evt);
            }
        });

        jlbl_viernes8_10.setText(" ");

        jbtn_lunes10_12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_lunes10_12.setText("Reservar");
        jbtn_lunes10_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_lunes10_12ActionPerformed(evt);
            }
        });

        jlbl_lunes10_12.setText(" ");

        jbtn_lunes12_14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_lunes12_14.setText("Reservar");
        jbtn_lunes12_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_lunes12_14ActionPerformed(evt);
            }
        });

        jlbl_lunes12_14.setText(" ");

        jbtn_lunes14_16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_lunes14_16.setText("Reservar");
        jbtn_lunes14_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_lunes14_16ActionPerformed(evt);
            }
        });

        jlbl_lunes14_16.setText(" ");

        jbtn_lunes16_18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_lunes16_18.setText("Reservar");
        jbtn_lunes16_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_lunes16_18ActionPerformed(evt);
            }
        });

        jlbl_lunes16_18.setText(" ");

        jlbl_martes16_18.setText(" ");

        jbtn_martes16_18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_martes16_18.setText("Reservar");
        jbtn_martes16_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_martes16_18ActionPerformed(evt);
            }
        });

        jlbl_martes14_16.setText(" ");

        jbtn_martes14_16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_martes14_16.setText("Reservar");
        jbtn_martes14_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_martes14_16ActionPerformed(evt);
            }
        });

        jlbl_martes12_14.setText(" ");

        jbtn_martes12_14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_martes12_14.setText("Reservar");
        jbtn_martes12_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_martes12_14ActionPerformed(evt);
            }
        });

        jlbl_martes10_12.setText(" ");

        jbtn_martes10_12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_martes10_12.setText("Reservar");
        jbtn_martes10_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_martes10_12ActionPerformed(evt);
            }
        });

        jlbl_lunes8_24.setText(" ");

        jbtn_miercoles16_18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_miercoles16_18.setText("Reservar");
        jbtn_miercoles16_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_miercoles16_18ActionPerformed(evt);
            }
        });

        jlbl_miercoles14_16.setText(" ");

        jbtn_miercoles14_16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_miercoles14_16.setText("Reservar");
        jbtn_miercoles14_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_miercoles14_16ActionPerformed(evt);
            }
        });

        jlbl_miercoles12_14.setText(" ");

        jbtn_miercoles12_14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_miercoles12_14.setText("Reservar");
        jbtn_miercoles12_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_miercoles12_14ActionPerformed(evt);
            }
        });

        jlbl_miercoles10_12.setText(" ");

        jbtn_miercoles10_12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_miercoles10_12.setText("Reservar");
        jbtn_miercoles10_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_miercoles10_12ActionPerformed(evt);
            }
        });

        jlbl_jueves16_18.setText(" ");

        jbtn_jueves16_18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_jueves16_18.setText("Reservar");
        jbtn_jueves16_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_jueves16_18ActionPerformed(evt);
            }
        });

        jlbl_jueves14_16.setText(" ");

        jbtn_jueves14_16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_jueves14_16.setText("Reservar");
        jbtn_jueves14_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_jueves14_16ActionPerformed(evt);
            }
        });

        jlbl_jueves12_14.setText(" ");

        jbtn_jueves12_14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_jueves12_14.setText("Reservar");
        jbtn_jueves12_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_jueves12_14ActionPerformed(evt);
            }
        });

        jlbl_jueves10_12.setText(" ");

        jbtn_jueves10_12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_jueves10_12.setText("Reservar");
        jbtn_jueves10_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_jueves10_12ActionPerformed(evt);
            }
        });

        jbtn_viernes16_18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_viernes16_18.setText("Reservar");
        jbtn_viernes16_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viernes16_18ActionPerformed(evt);
            }
        });

        jlbl_viernes14_16.setText(" ");

        jbtn_viernes14_16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_viernes14_16.setText("Reservar");
        jbtn_viernes14_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viernes14_16ActionPerformed(evt);
            }
        });

        jlbl_viernes12_14.setText(" ");

        jbtn_viernes12_14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_viernes12_14.setText("Reservar");
        jbtn_viernes12_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viernes12_14ActionPerformed(evt);
            }
        });

        jlbl_viernes10_12.setText(" ");

        jbtn_viernes10_12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_viernes10_12.setText("Reservar");
        jbtn_viernes10_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_viernes10_12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_lunes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_lunes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_lunes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_lunes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_lunes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbl_lunes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbl_lunes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbl_lunes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbl_lunes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbl_lunes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_martes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_miercoles8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtn_viernes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtn_viernes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtn_viernes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtn_viernes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jbtn_jueves8_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn_viernes8_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(47, 47, 47))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jlbl_martes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jlbl_miercoles8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jlbl_jueves8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jlbl_viernes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_martes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_martes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_martes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_martes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_martes10_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_martes12_14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_martes14_16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_martes16_18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_miercoles10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_miercoles12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_miercoles14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_miercoles16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_miercoles10_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_miercoles12_14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_miercoles14_16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_lunes8_24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtn_jueves10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn_jueves12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn_jueves14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn_jueves16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jlbl_jueves10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbl_viernes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jlbl_jueves12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbl_viernes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jlbl_jueves14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbl_viernes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jlbl_jueves16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbl_viernes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_martes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_lunes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtn_miercoles8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtn_jueves8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtn_viernes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_lunes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_martes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_miercoles8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_jueves8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_viernes8_10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_lunes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_lunes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_lunes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_lunes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_lunes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_lunes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_lunes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_lunes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_miercoles10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_miercoles10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_miercoles12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_miercoles12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_miercoles14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_miercoles14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_miercoles16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_lunes8_24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_jueves10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_jueves10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_jueves12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_jueves12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_jueves14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_jueves14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_jueves16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_jueves16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_viernes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_viernes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_viernes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_viernes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_viernes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_viernes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_viernes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jlbl_viernes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_martes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jlbl_martes10_12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_martes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jlbl_martes12_14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_martes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jlbl_martes14_16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_martes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jlbl_martes16_18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("8:00 a 10:00 AM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("10:00 a 12:00 PM");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("12:00 a 14:00 PM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("14:00 a 16:00 PM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("16:00 a 18:00 PM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jbtn_Limpiar.setText("Limpiar");
        jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LimpiarActionPerformed(evt);
            }
        });

        jbtn_cerrarSesion.setText("Cerrar Sesion");
        jbtn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cerrarSesionActionPerformed(evt);
            }
        });

        jbtn_cerrar_Sesion.setText("Cerrar Sesion");
        jbtn_cerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cerrar_SesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_lunes8_14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_cerrar_Sesion)
                            .addComponent(jbtn_Limpiar))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(914, 914, 914)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(473, 473, 473)
                    .addComponent(jbtn_cerrarSesion)
                    .addContainerGap(476, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jlbl_lunes8_14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jbtn_Limpiar)
                                .addGap(40, 40, 40)
                                .addComponent(jbtn_cerrar_Sesion)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(287, 287, 287)
                    .addComponent(jbtn_cerrarSesion)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_jueves8_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_jueves8_10ActionPerformed
       {                                               
       if(jbtn_jueves8_10.isSelected()){
           jbtn_jueves8_10.setBackground(Color.yellow);
           jbtn_jueves8_10.setText("Reservado");
           
       }else{
       jbtn_jueves8_10.setBackground(new Color(255,255,255));
       jbtn_jueves8_10.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_jueves8_10ActionPerformed

    private void jbtn_miercoles8_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_miercoles8_10ActionPerformed
       {                                               
       if(jbtn_miercoles8_10.isSelected()){
           jbtn_miercoles8_10.setBackground(Color.yellow);
           jbtn_miercoles8_10.setText("Reservado");
           
       }else{
       jbtn_miercoles8_10.setBackground(new Color(255,255,255));
       jbtn_miercoles8_10.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_miercoles8_10ActionPerformed

    private void jbtn_martes8_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_martes8_10ActionPerformed
        {                                               
       if(jbtn_martes8_10.isSelected()){
           jbtn_martes8_10.setBackground(Color.yellow);
           jbtn_martes8_10.setText("Reservado");
           
       }else{
       jbtn_martes8_10.setBackground(new Color(255,255,255));
       jbtn_martes8_10.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_martes8_10ActionPerformed

    private void jbtn_lunes8_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_lunes8_10ActionPerformed
       if(jbtn_lunes8_10.isSelected()){
           jbtn_lunes8_10.setBackground(Color.yellow);
           jbtn_lunes8_10.setText("Reservado");
           
       }else{
       jbtn_lunes8_10.setBackground(new Color(255,255,255));
       jbtn_lunes8_10.setText("Reservar");
       }
    }//GEN-LAST:event_jbtn_lunes8_10ActionPerformed

    private void jbtn_viernes8_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viernes8_10ActionPerformed
       {                                               
       if(jbtn_viernes8_10.isSelected()){
           jbtn_viernes8_10.setBackground(Color.yellow);
           jbtn_viernes8_10.setText("Reservado");
           
       }else{
       jbtn_viernes8_10.setBackground(new Color(255,255,255));
       jbtn_viernes8_10.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_viernes8_10ActionPerformed

    private void jbtn_lunes10_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_lunes10_12ActionPerformed
        {                                               
       if(jbtn_lunes10_12.isSelected()){
           jbtn_lunes10_12.setBackground(Color.yellow);
           jbtn_lunes10_12.setText("Reservado");
           
       }else{
       jbtn_lunes10_12.setBackground(new Color(255,255,255));
       jbtn_lunes10_12.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_lunes10_12ActionPerformed

    private void jbtn_lunes12_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_lunes12_14ActionPerformed
        {                                               
       if(jbtn_lunes12_14.isSelected()){
           jbtn_lunes12_14.setBackground(Color.yellow);
           jbtn_lunes12_14.setText("Reservado");
           
       }else{
       jbtn_lunes12_14.setBackground(new Color(255,255,255));
       jbtn_lunes12_14.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_lunes12_14ActionPerformed

    private void jbtn_lunes14_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_lunes14_16ActionPerformed
       {                                               
       if(jbtn_lunes14_16.isSelected()){
           jbtn_lunes14_16.setBackground(Color.yellow);
           jbtn_lunes14_16.setText("Reservado");
           
       }else{
       jbtn_lunes14_16.setBackground(new Color(255,255,255));
       jbtn_lunes14_16.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_lunes14_16ActionPerformed

    private void jbtn_lunes16_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_lunes16_18ActionPerformed
       {                                               
       if(jbtn_lunes16_18.isSelected()){
           jbtn_lunes16_18.setBackground(Color.yellow);
           jbtn_lunes16_18.setText("Reservado");
           
       }else{
       jbtn_lunes16_18.setBackground(new Color(255,255,255));
       jbtn_lunes16_18.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_lunes16_18ActionPerformed

    private void jbtn_martes16_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_martes16_18ActionPerformed
       {                                               
       if(jbtn_martes16_18.isSelected()){
           jbtn_martes16_18.setBackground(Color.yellow);
           jbtn_martes16_18.setText("Reservado");
           
       }else{
       jbtn_martes16_18.setBackground(new Color(255,255,255));
       jbtn_martes16_18.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_martes16_18ActionPerformed

    private void jbtn_martes14_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_martes14_16ActionPerformed
     {                                               
       if(jbtn_martes14_16.isSelected()){
           jbtn_martes14_16.setBackground(Color.yellow);
           jbtn_martes14_16.setText("Reservado");
           
       }else{
       jbtn_martes14_16.setBackground(new Color(255,255,255));
       jbtn_martes14_16.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_martes14_16ActionPerformed

    private void jbtn_martes12_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_martes12_14ActionPerformed
        {                                               
       if(jbtn_martes12_14.isSelected()){
           jbtn_martes12_14.setBackground(Color.yellow);
           jbtn_martes12_14.setText("Reservado");
           
       }else{
       jbtn_martes12_14.setBackground(new Color(255,255,255));
       jbtn_martes12_14.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_martes12_14ActionPerformed

    private void jbtn_martes10_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_martes10_12ActionPerformed
       {                                               
       if(jbtn_martes10_12.isSelected()){
           jbtn_martes10_12.setBackground(Color.yellow);
           jbtn_martes10_12.setText("Reservado");
           
       }else{
       jbtn_martes10_12.setBackground(new Color(255,255,255));
       jbtn_martes10_12.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_martes10_12ActionPerformed

    private void jbtn_miercoles16_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_miercoles16_18ActionPerformed
       {                                               
       if(jbtn_miercoles16_18.isSelected()){
           jbtn_miercoles16_18.setBackground(Color.yellow);
           jbtn_miercoles16_18.setText("Reservado");
           
       }else{
       jbtn_miercoles16_18.setBackground(new Color(255,255,255));
       jbtn_miercoles16_18.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_miercoles16_18ActionPerformed

    private void jbtn_miercoles14_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_miercoles14_16ActionPerformed
        {                                               
       if(jbtn_miercoles14_16.isSelected()){
           jbtn_miercoles14_16.setBackground(Color.yellow);
           jbtn_miercoles14_16.setText("Reservado");
           
       }else{
       jbtn_miercoles14_16.setBackground(new Color(255,255,255));
       jbtn_miercoles14_16.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_miercoles14_16ActionPerformed

    private void jbtn_miercoles12_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_miercoles12_14ActionPerformed
       {                                               
       if(jbtn_miercoles12_14.isSelected()){
           jbtn_miercoles12_14.setBackground(Color.yellow);
           jbtn_miercoles12_14.setText("Reservado");
           
       }else{
       jbtn_miercoles12_14.setBackground(new Color(255,255,255));
       jbtn_miercoles12_14.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_miercoles12_14ActionPerformed

    private void jbtn_miercoles10_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_miercoles10_12ActionPerformed
       {                                               
       if(jbtn_miercoles10_12.isSelected()){
           jbtn_miercoles10_12.setBackground(Color.yellow);
           jbtn_miercoles10_12.setText("Reservado");
           
       }else{
       jbtn_miercoles10_12.setBackground(new Color(255,255,255));
       jbtn_miercoles10_12.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_miercoles10_12ActionPerformed

    private void jbtn_jueves16_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_jueves16_18ActionPerformed
       {                                               
       if(jbtn_jueves16_18.isSelected()){
           jbtn_jueves16_18.setBackground(Color.yellow);
           jbtn_jueves16_18.setText("Reservado");
           
       }else{
       jbtn_jueves16_18.setBackground(new Color(255,255,255));
       jbtn_jueves16_18.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_jueves16_18ActionPerformed

    private void jbtn_jueves14_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_jueves14_16ActionPerformed
        {                                               
       if(jbtn_jueves14_16.isSelected()){
           jbtn_jueves14_16.setBackground(Color.yellow);
           jbtn_jueves14_16.setText("Reservado");
           
       }else{
       jbtn_jueves14_16.setBackground(new Color(255,255,255));
       jbtn_jueves14_16.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_jueves14_16ActionPerformed

    private void jbtn_jueves12_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_jueves12_14ActionPerformed
       {                                               
       if(jbtn_jueves12_14.isSelected()){
           jbtn_jueves12_14.setBackground(Color.yellow);
           jbtn_jueves12_14.setText("Reservado");
           
       }else{
       jbtn_jueves12_14.setBackground(new Color(255,255,255));
       jbtn_jueves12_14.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_jueves12_14ActionPerformed

    private void jbtn_jueves10_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_jueves10_12ActionPerformed
       {                                               
       if(jbtn_jueves10_12.isSelected()){
           jbtn_jueves10_12.setBackground(Color.yellow);
           jbtn_jueves10_12.setText("Reservado");
           
       }else{
       jbtn_jueves10_12.setBackground(new Color(255,255,255));
       jbtn_jueves10_12.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_jueves10_12ActionPerformed

    private void jbtn_viernes16_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viernes16_18ActionPerformed
       {                                               
       if(jbtn_viernes16_18.isSelected()){
           jbtn_viernes16_18.setBackground(Color.yellow);
           jbtn_viernes16_18.setText("Reservado");
           
       }else{
       jbtn_viernes16_18.setBackground(new Color(255,255,255));
       jbtn_viernes16_18.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_viernes16_18ActionPerformed

    private void jbtn_viernes14_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viernes14_16ActionPerformed
        {                                               
       if(jbtn_viernes14_16.isSelected()){
           jbtn_viernes14_16.setBackground(Color.yellow);
           jbtn_viernes14_16.setText("Reservado");
           
       }else{
       jbtn_viernes14_16.setBackground(new Color(255,255,255));
       jbtn_viernes14_16.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_viernes14_16ActionPerformed

    private void jbtn_viernes12_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viernes12_14ActionPerformed
       {                                               
       if(jbtn_viernes12_14.isSelected()){
           jbtn_viernes12_14.setBackground(Color.yellow);
           jbtn_viernes12_14.setText("Reservado");
           
       }else{
       jbtn_viernes12_14.setBackground(new Color(255,255,255));
       jbtn_viernes12_14.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_viernes12_14ActionPerformed

    private void jbtn_viernes10_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_viernes10_12ActionPerformed
       {                                               
       if(jbtn_viernes10_12.isSelected()){
           jbtn_viernes10_12.setBackground(Color.yellow);
           jbtn_viernes10_12.setText("Reservado");
           
       }else{
       jbtn_viernes10_12.setBackground(new Color(255,255,255));
       jbtn_viernes10_12.setText("Reservar");
       }
    }
    }//GEN-LAST:event_jbtn_viernes10_12ActionPerformed

    private void jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LimpiarActionPerformed
    jbtn_jueves8_10.setText("");
    jbtn_jueves10_12.setText("");
    jbtn_jueves12_14.setText("");
    jbtn_jueves14_16.setText("");
    jbtn_jueves16_18.setText("");
    jbtn_lunes8_10.setText("");
    jbtn_lunes10_12.setText("");
    jbtn_lunes12_14.setText("");
    jbtn_lunes14_16.setText("");
    jbtn_lunes16_18.setText("");        
    jbtn_miercoles8_10.setText("");
    jbtn_miercoles10_12.setText("");
    jbtn_miercoles12_14.setText("");
    jbtn_miercoles14_16.setText("");
    jbtn_miercoles16_18.setText("");        
    jbtn_martes8_10.setText("");
    jbtn_martes10_12.setText("");
    jbtn_martes12_14.setText("");
    jbtn_martes14_16.setText("");
    jbtn_martes16_18.setText("");        
    jbtn_viernes8_10.setText("");
    jbtn_viernes10_12.setText("");
    jbtn_viernes12_14.setText("");
    jbtn_viernes14_16.setText("");
    jbtn_viernes16_18.setText("");        
    jlbl_lunes8_10.setText("");
    jlbl_lunes10_12.setText("");
    jlbl_lunes12_14.setText("");
    jlbl_lunes14_16.setText("");
    jlbl_lunes16_18.setText("");
    jlbl_martes8_10.setText("");
    jlbl_martes10_12.setText("");
    jlbl_martes12_14.setText("");
    jlbl_martes14_16.setText("");
    jlbl_martes16_18.setText("");        
    jlbl_miercoles8_10.setText("");
    jlbl_miercoles10_12.setText("");
    jlbl_miercoles12_14.setText("");
    jlbl_miercoles14_16.setText("");
    jlbl_lunes8_24.setText("");        
    jlbl_jueves8_10.setText("");
    jbtn_jueves10_12.setText("");
    jlbl_jueves12_14.setText("");
    jlbl_jueves14_16.setText("");
    jlbl_jueves16_18.setText("");        
    jlbl_viernes8_10.setText("");
    jlbl_viernes10_12.setText("");
    jlbl_viernes12_14.setText("");
    jlbl_viernes14_16.setText("");
    jlbl_viernes16_18.setText(""); 
    jbtn_jueves8_10.setText("Reservar");
    jbtn_jueves10_12.setText("Reservar");
    jbtn_jueves12_14.setText("Reservar");
    jbtn_jueves14_16.setText("Reservar");
    jbtn_jueves16_18.setText("Reservar");
    jbtn_lunes8_10.setText("Reservar");
    jbtn_lunes10_12.setText("Reservar");
    jbtn_lunes12_14.setText("Reservar");
    jbtn_lunes14_16.setText("Reservar");
    jbtn_lunes16_18.setText("Reservar");        
    jbtn_miercoles8_10.setText("Reservar");
    jbtn_miercoles10_12.setText("Reservar");
    jbtn_miercoles12_14.setText("Reservar");
    jbtn_miercoles14_16.setText("Reservar");
    jbtn_miercoles16_18.setText("Reservar");       
    jbtn_martes8_10.setText("Reservar");
    jbtn_martes10_12.setText("Reservar");
    jbtn_martes12_14.setText("Reservar");
    jbtn_martes14_16.setText("Reservar");
    jbtn_martes16_18.setText("Reservar");      
    jbtn_viernes8_10.setText("Reservar");
    jbtn_viernes10_12.setText("Reservar");
    jbtn_viernes12_14.setText("Reservar");
    jbtn_viernes14_16.setText("Reservar");
    jbtn_viernes16_18.setText("Reservar");
    jbtn_jueves8_10.setBackground(new Color(255,255,255));
    jbtn_jueves10_12.setBackground(new Color(255,255,255));
    jbtn_jueves12_14.setBackground(new Color(255,255,255));
    jbtn_jueves14_16.setBackground(new Color(255,255,255));
    jbtn_jueves16_18.setBackground(new Color(255,255,255));
    jbtn_lunes8_10.setBackground(new Color(255,255,255));
    jbtn_lunes10_12.setBackground(new Color(255,255,255));
    jbtn_lunes12_14.setBackground(new Color(255,255,255));
    jbtn_lunes14_16.setBackground(new Color(255,255,255));
    jbtn_lunes16_18.setBackground(new Color(255,255,255));        
    jbtn_miercoles8_10.setBackground(new Color(255,255,255));
    jbtn_miercoles10_12.setBackground(new Color(255,255,255));
    jbtn_miercoles12_14.setBackground(new Color(255,255,255));
    jbtn_miercoles14_16.setBackground(new Color(255,255,255));
    jbtn_miercoles16_18.setBackground(new Color(255,255,255));       
    jbtn_martes8_10.setBackground(new Color(255,255,255));
    jbtn_martes10_12.setBackground(new Color(255,255,255));
    jbtn_martes12_14.setBackground(new Color(255,255,255));
    jbtn_martes14_16.setBackground(new Color(255,255,255));
    jbtn_martes16_18.setBackground(new Color(255,255,255));      
    jbtn_viernes8_10.setBackground(new Color(255,255,255));
    jbtn_viernes10_12.setBackground(new Color(255,255,255));
    jbtn_viernes12_14.setBackground(new Color(255,255,255));
    jbtn_viernes14_16.setBackground(new Color(255,255,255));
    jbtn_viernes16_18.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jbtn_LimpiarActionPerformed

    private void jbtn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cerrarSesionActionPerformed
        JF_Inicio_Sesion newframe = new JF_Inicio_Sesion();

        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_cerrarSesionActionPerformed

    private void jbtn_cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cerrar_SesionActionPerformed
        JF_Inicio_Sesion newframe = new JF_Inicio_Sesion();

        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_cerrar_SesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbtn_Limpiar;
    private javax.swing.JButton jbtn_cerrarSesion;
    private javax.swing.JButton jbtn_cerrar_Sesion;
    private javax.swing.JToggleButton jbtn_jueves10_12;
    private javax.swing.JToggleButton jbtn_jueves12_14;
    private javax.swing.JToggleButton jbtn_jueves14_16;
    private javax.swing.JToggleButton jbtn_jueves16_18;
    private javax.swing.JToggleButton jbtn_jueves8_10;
    private javax.swing.JToggleButton jbtn_lunes10_12;
    private javax.swing.JToggleButton jbtn_lunes12_14;
    private javax.swing.JToggleButton jbtn_lunes14_16;
    private javax.swing.JToggleButton jbtn_lunes16_18;
    private javax.swing.JToggleButton jbtn_lunes8_10;
    private javax.swing.JToggleButton jbtn_martes10_12;
    private javax.swing.JToggleButton jbtn_martes12_14;
    private javax.swing.JToggleButton jbtn_martes14_16;
    private javax.swing.JToggleButton jbtn_martes16_18;
    private javax.swing.JToggleButton jbtn_martes8_10;
    private javax.swing.JToggleButton jbtn_miercoles10_12;
    private javax.swing.JToggleButton jbtn_miercoles12_14;
    private javax.swing.JToggleButton jbtn_miercoles14_16;
    private javax.swing.JToggleButton jbtn_miercoles16_18;
    private javax.swing.JToggleButton jbtn_miercoles8_10;
    private javax.swing.JToggleButton jbtn_viernes10_12;
    private javax.swing.JToggleButton jbtn_viernes12_14;
    private javax.swing.JToggleButton jbtn_viernes14_16;
    private javax.swing.JToggleButton jbtn_viernes16_18;
    private javax.swing.JToggleButton jbtn_viernes8_10;
    private javax.swing.JLabel jlbl_jueves10_12;
    private javax.swing.JLabel jlbl_jueves12_14;
    private javax.swing.JLabel jlbl_jueves14_16;
    private javax.swing.JLabel jlbl_jueves16_18;
    private javax.swing.JLabel jlbl_jueves8_10;
    private javax.swing.JLabel jlbl_lunes10_12;
    private javax.swing.JLabel jlbl_lunes12_14;
    private javax.swing.JLabel jlbl_lunes14_16;
    private javax.swing.JLabel jlbl_lunes16_18;
    private javax.swing.JLabel jlbl_lunes8_10;
    private javax.swing.JLabel jlbl_lunes8_14;
    private javax.swing.JLabel jlbl_lunes8_24;
    private javax.swing.JLabel jlbl_martes10_12;
    private javax.swing.JLabel jlbl_martes12_14;
    private javax.swing.JLabel jlbl_martes14_16;
    private javax.swing.JLabel jlbl_martes16_18;
    private javax.swing.JLabel jlbl_martes8_10;
    private javax.swing.JLabel jlbl_miercoles10_12;
    private javax.swing.JLabel jlbl_miercoles12_14;
    private javax.swing.JLabel jlbl_miercoles14_16;
    private javax.swing.JLabel jlbl_miercoles8_10;
    private javax.swing.JLabel jlbl_viernes10_12;
    private javax.swing.JLabel jlbl_viernes12_14;
    private javax.swing.JLabel jlbl_viernes14_16;
    private javax.swing.JLabel jlbl_viernes16_18;
    private javax.swing.JLabel jlbl_viernes8_10;
    // End of variables declaration//GEN-END:variables
}
